version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP access
      - "7687:7687"  # Bolt protocol access
    environment:
      - NEO4J_AUTH=neo4j/huhontow  # Set the default password for the Neo4j database
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "huhontow", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - tenji
    
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      neo4j:
        condition: service_healthy
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=huhontow
      - NEO4J_ENCRYPTION=ENCRYPTION_OFF
    command: npm run dev
    networks:
      - tenji
  
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    networks:
      - tenji


networks:
  tenji:

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: